### ISSUE TITLE
Failed to highlight code when contains captions

### ISSUE THREAD

**Issue by NoahDragon** [ele828/hexo-prism-plugin#19]
I have encountered the following issue when the code block has a caption, it fails to recognize as a code block. For example the following code block for `bash git_commit_source.sh`

![image](https://cloud.githubusercontent.com/assets/5704064/25205095/ac899a70-252e-11e7-8ae5-b94faafbbc37.png)

**Comment by ele828** [comment]
Fixed #21

**Comment by vagyriag** [comment]
I'm still having this issue? 
should I add something different?

this works:
![image](https://user-images.githubusercontent.com/4133176/30487543-62bb1fd2-99f9-11e7-8469-3fa01326ab37.png)

this doesn't
![image](https://user-images.githubusercontent.com/4133176/30487529-58080352-99f9-11e7-9a16-309de7099c1d.png)

thank you
